version: '2.1'
services:
    ###################
    ##    BACKEND    ##
    ###################

    xotomicro-back-auth-service:
        build:
            context: .
            dockerfile: docker/dockerfile.development
        container_name: xotomicro-back-auth-service-dev
        image: xotomicro-back-auth-service-dev
        environment:
            - SECRET_KEY=${SECRET_KEY}
            - JVM_OPTS=-Xmx512m -Xms512m
            - PROFILE=${PROFILE}
            - ENV=${ENV}
        ports:
            - 8082:8082
        healthcheck:
            test: ['CMD', 'curl', '-f', 'http://localhost:8082/actuator/health']
            interval: 30s
            timeout: 1s
            retries: 10
        volumes:
            - ./:/app
        env_file:
            - .env
